version: "3.9"
services:
    caddy:
        depends_on:
            - db
            - liberty
        profiles: ["caddy"]
        image: caddy:2
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile

    db:
        # TODO: grant swtp access in conf script
        image: mysql:8.0.29
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            #MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_DATABASE: "swtp"
            #MYSQL_USER: "swtp"
            #MYSQL_PASSWORD: "swtp"
        volumes:
            - ./database/conf/:/etc/mysql/conf.d
            - ./database/initdb/:/docker-entrypoint-initdb.d/

    liberty:
        depends_on:
            - db
        build: .
        profiles: ["prod"]
        ports:
            - "9080:9080"
            - "9443:9443"
        environment:
            DB_HOSTNAME: "db"

        #volumes:
        #    - ./src/main/liberty/config/:/config/
        #    - ./target/take-me-along.war:/config/apps/take-me-along.war
        restart: unless-stopped

    adminer:
        image: adminer
        profiles: ["dev"]
        restart: unless-stopped
        ports:
            - 8080:8080
