version: "3.9"
services:
    db:
        build: ./database
        ports:
            - "3306:3306"
        restart: unless-stopped

    liberty:
        build: ./src
        ports:
            - "9443:9443"
        restart: unless-stopped
    redis:
        image: "redis:alpine"

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
